// let h={
//     name:'aswanth',
//     age:90
// }

// let m={
//     name:'ajmal'
// }

// m.__proto__=h
// console.log(m.place );

db.userss.insertMany([{
    name: "Garvin",
    email: "gtuckerman0@chron.com",
    gender: "Male",
    country: "Indonesia",
    age: 32
  }, {
    name: "Tessi",
    email: "twenman1@odnoklassniki.ru",
    gender: "Female",
    country: "Palestinian Territory",
    age: 34
  }, {
    name: "Claudia",
    email: "cpetrowsky2@bandcamp.com",
    gender: "Female",
    country: "Poland",
    age: 25
  }, {
    name: "Jamal",
    email: "jdagostino3@fda.gov",
    gender: "Male",
    country: "Poland",
    age: 41
  }, {
    name: "Timmy",
    email: "trobertsson4@sitemeter.com",
    gender: "Female",
    country: "France",
    age: 31
  }, {
    name: "Sonni",
    email: "sclavering5@ebay.co.uk",
    gender: "Female",
    country: "Liberia",
    age: 35
  }, {
    name: "Bryana",
    email: "bskey6@topsy.com",
    gender: "Female",
    country: "France",
    age: 44
  }, {
    name: "Carmel",
    email: "caudibert7@hc360.com",
    gender: "Female",
    country: "Spain",
    age: 41
  }, {
    name: "Korey",
    email: "kreddel8@mac.com",
    gender: "Male",
    country: "China",
    age: 39
  }, {
    name: "Keary",
    email: "kmaffioni9@cyberchimps.com",
    gender: "Male",
    country: "Japan",
    age: 16
  }, {
    name: "Neddie",
    email: "nbeamesa@nature.com",
    gender: "Polygender",
    country: "China",
    age: 27
  }, {
    name: "Viva",
    email: "vlesurfb@unicef.org",
    gender: "Female",
    country: "Netherlands",
    age: 21
  }, {
    name: "Rudolf",
    email: "rfissendenc@wikimedia.org",
    gender: "Non-binary",
    country: "China",
    age: 29
  }, {
    name: "Adella",
    email: "ajenneyd@geocities.com",
    gender: "Female",
    country: "Tanzania",
    age: 16
  }, {
    name: "Candide",
    email: "chariote@furl.net",
    gender: "Female",
    country: "Mexico",
    age: 15
  }, {
    name: "Dur",
    email: "dantonomolif@va.gov",
    gender: "Bigender",
    country: "Suriname",
    age: 33
  }, {
    name: "Jasper",
    email: "jhowoodg@chicagotribune.com",
    gender: "Male",
    country: "United States",
    age: 33
  }, {
    name: "Dame",
    email: "ddomangeh@prweb.com",
    gender: "Male",
    country: "Philippines",
    age: 41
  }, {
    name: "Northrop",
    email: "nbroki@bravesites.com",
    gender: "Male",
    country: "China",
    age: 32
  }, {
    name: "Romona",
    email: "rlindberghj@live.com",
    gender: "Female",
    country: "China",
    age: 34
  }, {
    name: "Jerrilyn",
    email: "jgoldsbyk@ameblo.jp",
    gender: "Female",
    country: "China",
    age: 30
  }, {
    name: "Itch",
    email: "ibonairel@soup.io",
    gender: "Male",
    country: "Poland",
    age: 23
  }, {
    name: "Zelig",
    email: "zleggism@gizmodo.com",
    gender: "Male",
    country: "Nigeria",
    age: 30
  }, {
    name: "Cassius",
    email: "cbladern@feedburner.com",
    gender: "Male",
    country: "Iran",
    age: 20
  }, {
    name: "Starlene",
    email: "sellwando@vk.com",
    gender: "Female",
    country: "Peru",
    age: 26
  }, {
    name: "Alexandre",
    email: "apaddockp@devhub.com",
    gender: "Male",
    country: "Finland",
    age: 42
  }, {
    name: "Jerrie",
    email: "jpreddleq@spiegel.de",
    gender: "Male",
    country: "Indonesia",
    age: 42
  }, {
    name: "Eli",
    email: "eshirdr@eventbrite.com",
    gender: "Male",
    country: "China",
    age: 27
  }, {
    name: "Noella",
    email: "nmcveighs@360.cn",
    gender: "Agender",
    country: "Indonesia",
    age: 29
  }, {
    name: "Cariotta",
    email: "cminorst@nytimes.com",
    gender: "Polygender",
    country: "China",
    age: 22
  }, {
    name: "Edmund",
    email: "ewychardu@reverbnation.com",
    gender: "Male",
    country: "Colombia",
    age: 23
  }, {
    name: "Liesa",
    email: "lodav@toplist.cz",
    gender: "Female",
    country: "Finland",
    age: 43
  }, {
    name: "Addi",
    email: "aprendergrastw@qq.com",
    gender: "Female",
    country: "China",
    age: 19
  }, {
    name: "Shirl",
    email: "sfurzeyx@ustream.tv",
    gender: "Female",
    country: "New Zealand",
    age: 43
  }, {
    name: "Lura",
    email: "lturnelly@illinois.edu",
    gender: "Female",
    country: "Mexico",
    age: 18
  }, {
    name: "Hewett",
    email: "hhallorz@discuz.net",
    gender: "Male",
    country: "China",
    age: 31
  }, {
    name: "Eberto",
    email: "ecohr10@fda.gov",
    gender: "Male",
    country: "France",
    age: 26
  }, {
    name: "Haze",
    email: "hreadings11@forbes.com",
    gender: "Bigender",
    country: "China",
    age: 26
  }, {
    name: "Karolina",
    email: "kgrimditch12@friendfeed.com",
    gender: "Female",
    country: "Paraguay",
    age: 25
  }, {
    name: "Graham",
    email: "gfurley13@thetimes.co.uk",
    gender: "Male",
    country: "Kazakhstan",
    age: 33
  }, {
    name: "Farrell",
    email: "fdanat14@mozilla.org",
    gender: "Male",
    country: "Poland",
    age: 42
  }, {
    name: "Salim",
    email: "selsley15@youtu.be",
    gender: "Male",
    country: "China",
    age: 45
  }, {
    name: "Jorey",
    email: "jodgers16@eepurl.com",
    gender: "Female",
    country: "Sweden",
    age: 35
  }, {
    name: "Keelia",
    email: "kwint17@deliciousdays.com",
    gender: "Female",
    country: "Russia",
    age: 18
  }, {
    name: "Kalindi",
    email: "kroseman18@europa.eu",
    gender: "Female",
    country: "United States",
    age: 39
  }, {
    name: "Dex",
    email: "dgoodwell19@xinhuanet.com",
    gender: "Male",
    country: "France",
    age: 28
  }, {
    name: "Marmaduke",
    email: "mlancaster1a@icq.com",
    gender: "Male",
    country: "Philippines",
    age: 44
  }, {
    name: "Dougie",
    email: "dsenn1b@purevolume.com",
    gender: "Male",
    country: "New Zealand",
    age: 26
  }, {
    name: "Henriette",
    email: "hbolzen1c@chronoengine.com",
    gender: "Female",
    country: "Indonesia",
    age: 19
  }, {
    name: "Catrina",
    email: "ccahn1d@tiny.cc",
    gender: "Genderfluid",
    country: "China",
    age: 18
  }])